name: Docker tests
on: [push]

jobs:
  my_first_job:
    steps:
    - name: My first step
      uses: docker://alpine:3.8
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
